name: "GitHub Actions Notifier for Slack"
description: "Send a Slack notification when a failed build becomes green again"
author: "DevOps team"
branding:
  icon: "message-square"
  color: "green"
runs:
  using: "docker"
  image: image: "docker://rplan/slack-action:v2.1.0"
