name: "GitHub Actions Notifier for Slack"
description: "Send a Slack notification when a failed build becomes green again"
author: "DevOps team"
branding:
  icon: "message-square"
  color: "green"

jobs:
  notify:
    runs-on: ubuntu-latest
    container: 
      image: europe-west3-docker.pkg.dev/allex-artifacts/allex-artifacts-docker/rplan-slack-action:v2.1.0

    steps:
      # Authenticate with Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # Set up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
