name: "GitHub Actions Notifier for Slack"
description: "Send a Slack notification when a failed build becomes green again"
author: "DevOps team"
branding:
  icon: "message-square"
  color: "green"
runs:
  # using: "docker"
  # image: "docker://rplan/slack-action:v2.1.0"
  repository: europe-west3-docker.pkg.dev/allex-artifacts/allex-artifacts-docker/rplan-slack-action
  tag: v2.1.0

